openapi: 3.0.0
components:
  schemas:
    Product:
      count: 2
      description: '[MOCK] Short Product Descriptio1'
      id: 7567ec4b-b10c-48c5-9445-fc73c48a80a2
      price: 23
      title: '[MOCK] Product2'
  securitySchemes: {}
info:
  title: Products service API
  description: This is documentation for Product service API
  version: '1'
paths:
  '//products/{id}':
    get:
      operationId: getProductById
      summary: Retrieving all products
      responses:
        '200':
          description: Product
          content: {}
