service: products-service

frameworkVersion: '3'

useDotenv: true

custom:
  webpack:
    includeModules: true
  autoswagger:
    title: 'products-service'
    apiType: 'httpApi'
    typefiles: [ './types/product.d.ts' ]
    swaggerPath: 'swagger-ui'
    schemes: [ 'https' ]

provider:
  name: aws
  runtime: nodejs12.x
  httpApi:
    cors: true
  stage: dev
  region: eu-west-1

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          path: /products/{id}
          method: get
          summary: "Get product by id"
          description: "Returns product by provided id"
          queryStringParameters:
            id:
              required: true
              type: 'string'
              description: 'Product id'
          responseData:
            200:
              bodyType: 'Product'

  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          summary: "Get list of products"
          description: "Returns all products"
          responseData:
            200:
              bodyType: 'Product[]'
